const { _electron: electron } = require('playwright')
const { resolve, join } = require('node:path')
const fs = require('node:fs/promises')
const { execFileSync } = require('node:child_process')
const assert = require('node:assert/strict')
const { createHash } = require('node:crypto')
const root=resolve(__dirname,'../..')
const exe=process.env.PHOTO_TEST_EXE||resolve(__dirname,'../dist/win-unpacked/Photo Workflow.exe')
const resources=join(exe,'../resources/backend')
const home=join(root,'.cache/desktop-smoke-'+Date.now())
const hash=bytes=>createHash('sha256').update(bytes).digest('hex')
let app
async function launch(){
  const env={...process.env,PHOTOWORKFLOW_HOME:home};delete env.ELECTRON_RUN_AS_NODE
  app=await electron.launch({executablePath:exe,env,timeout:60000})
  console.log('Electron launched')
  app.process().stderr.on('data',data=>console.log(String(data).slice(0,1000)))
  const page=await app.firstWindow();await page.waitForLoadState('domcontentloaded')
  page.on('pageerror',error=>console.log('Renderer error',error))
  console.log('Window loaded',await page.title())
  await page.waitForFunction(()=>!!window.photo)
  return page
}
async function close(){
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close())
  await new Promise((resolve,reject)=>{const child=app.process();if(child.exitCode!==null)return resolve();const t=setTimeout(()=>reject(new Error('Backend shutdown timed out')),30000);child.once('exit',()=>{clearTimeout(t);resolve()})})
}
(async()=>{
  await fs.mkdir(home,{recursive:true})
  const fixture=join(home,'synthetic.png')
  execFileSync(join(resources,'python/python.exe'),['-c',`from PIL import Image; import numpy as np; a=np.zeros((128,192,3),dtype=np.uint8); a[:,:,0]=np.arange(192,dtype=np.uint8); a[:,:,1]=80; a[:,:,2]=120; Image.fromarray(a).save(${JSON.stringify(fixture)})`],{windowsHide:true})
  const original=hash(await fs.readFile(fixture)),evidence={fixture:'synthetic 192×128 gradient',checks:[]}
  let page=await launch()
  console.log('Bridge ready')
  const state=await page.evaluate(()=>window.photo.call('status'))
  console.log('Status received')
  assert.equal(state.home.toLowerCase(),home.toLowerCase());assert.equal(state.gpu.available,false)
  evidence.checks.push('Packaged Python starts without developer Python, CUDA runtime or models')
  assert.ok(state.dependencies.some(x=>x.group==='runtime'&&x.missingBytes>0))
  await app.evaluate(({dialog},fixture)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[fixture]})},fixture)
  await page.getByRole('button',{name:'Choose photo',exact:true}).click()
  await page.waitForFunction(()=>document.body.textContent.includes('synthetic.png'))
  evidence.checks.push('Native picker selection is accepted by the narrow bridge')
  const blocked=await page.evaluate(async()=>{try{await window.photo.call('execute',{command:'whoami'});return false}catch{return true}})
  console.log('Unknown method rejected');assert.ok(blocked);evidence.checks.push('Unknown privileged operation rejected')
  const noSession=await page.evaluate(async()=>{try{await window.photo.call('session',{});return false}catch(e){return String(e).includes('Install or repair')}})
  console.log('Missing assistant rejected');assert.ok(noSession);evidence.checks.push('Missing assistant dependency has an actionable error')
  const result=await page.evaluate(source=>window.photo.call('process',{source,operation:'edit',recipe:{exposure:.25,denoise:0}}),fixture)
  assert.equal(result.code,0)
  const jobs=await page.evaluate(()=>window.photo.call('results'));assert.equal(jobs.length,1)
  assert.equal(hash(await fs.readFile(fixture)),original)
  assert.equal(hash(await fs.readFile(join(jobs[0].path,'source.png'))),original)
  execFileSync(join(resources,'python/python.exe'),['-c',`import tifffile; a=tifffile.imread(${JSON.stringify(join(jobs[0].path,'composite.tif'))}); assert str(a.dtype)=='uint16'; assert a.shape==(128,192,3)`],{windowsHide:true})
  evidence.checks.push('Synthetic tone edit publishes 16-bit TIFF and preserves exact original bytes')
  const image=await page.evaluate(p=>window.photo.preview(p),join(jobs[0].path,'composite.tif'));assert.ok(image.startsWith('data:image/png;base64,'))
  await page.getByRole('button',{name:/Results/}).click()
  await page.getByRole('button',{name:new RegExp(jobs[0].name)}).click()
  await page.getByAltText('Local before and after photo comparison').waitFor()
  evidence.checks.push('Packaged result navigation and before/after preview load')
  const cancelled=await page.evaluate(async source=>{const p=window.photo.call('process',{source,operation:'edit',recipe:{exposure:.3,denoise:0}});await new Promise(r=>setTimeout(r,200));await window.photo.call('cancel');return p},fixture)
  assert.equal(cancelled.code,130);assert.equal((await page.evaluate(()=>window.photo.call('results'))).length,1)
  evidence.checks.push('Cancellation stops at backend boundary without publishing a partial result')
  await page.evaluate(()=>window.photo.call('settings',{value:{theme:'light',reviewZoom:'fit'}}))
  await close();page=await launch()
  assert.equal((await page.evaluate(()=>window.photo.call('settings'))).theme,'light')
  assert.equal((await page.evaluate(()=>window.photo.call('results'))).length,1)
  assert.equal(hash(await fs.readFile(fixture)),original)
  evidence.checks.push('Graceful shutdown/relaunch preserves settings, originals and outputs')
  await close();app=null
  evidence.status='passed';evidence.home=home;evidence.executable=exe
  await fs.writeFile(join(root,'.cache/desktop-smoke-report.json'),JSON.stringify(evidence,null,2))
  console.log(JSON.stringify(evidence,null,2))
})().catch(async error=>{console.error(error);if(app)await app.close().catch(()=>{});process.exitCode=1})
